// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadContextBaseline } from "./ThreadContextBaseline";
import type { TokenUsageBreakdown } from "./TokenUsageBreakdown";

export type ThreadTokenUsage = { total: TokenUsageBreakdown, last: TokenUsageBreakdown, modelContextWindow: number | null,
/**
 * What the part of the prompt the conversation cannot influence costs —
 * base instructions, tool schemas, output schema — as measured when the
 * request this event reports usage for was built.
 *
 * Null whenever no such measurement belongs to that request: before the
 * first one, for requests Codex builds without tools or an output schema
 * (compaction), and while `last` is a locally recomputed estimate rather
 * than a provider figure. Read null as "denominate against Codex's own
 * historical constant", not as "the previous value still applies".
 *
 * Nullable rather than optional, matching `model_context_window`, so the
 * generated TypeScript stays inside the export rules for non-params types.
 */
contextBaseline: ThreadContextBaseline | null, };
