// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * See `codex_protocol::protocol::ContextBaseline`. Approximate: priced with
 * the same byte-density heuristic Codex uses for history estimation, so it
 * describes a denominator and never replaces provider-reported usage.
 */
export type ThreadContextBaseline = { systemPromptTokens: number, toolSchemaTokens: number,
/**
 * Zero when the request carries no response-format schema.
 */
outputSchemaTokens: number,
/**
 * How many model-visible tool specs were sent. Exact.
 */
toolCount: number, };
